### ISSUE TITLE
system and data partitions missing?

### ISSUE THREAD

**Issue by oebs** [mrmazakblu/Device-TWRP-Umidigi-A7-Pro#1]
Device is A7 Pro 128 GB model, FW: UMIDIGI A7 PRO 128GB EEA V1.4_20200819
[df output in TWRP](https://del.dog/ymumefivig.txt)
[df output in stock recovery](https://del.dog/pupecyghek.txt)

**Comment by mrmazakblu** [comment]
Try to select system vendor and product from the mount menu first, then check if output.


Also how did you have adb work in stock recovery?

**Comment by oebs** [comment]
I'm sorry. Not sure if I've overseen it before. Reflashed TWRP and "System" is available. Mount Menu:

[ ] System
[ ] Vendor
[ ] Product
[ ] Metadata
[x] Cache
[x] Micro SD card
[ ] Usb-Otg

In other mobiles and also this one I was able to get a "adb shell" root shell in TWRP, but I'll retried and right now I never get a "adb devices" or "adb shell" working in TWRP again.

Mount of System, Vendor, Product did work. I don't see any Data / Userdata.

**Comment by oebs** [comment]
When I select "Backup" I see some partitions, but not "System" or "(User)data":

[ ] Metadata (0MB)
[ ] Super (3416MB)
[x] Boot (32MB)
[ ] Dtbo (8MB)
[ ] Cache (5MB(
[ ] Recovery (32MB)
[ ] super (3516MB(

**Comment by mrmazakblu** [comment]
As I know it, you cannot backup system not flash system.img only the whole super partition. Which is system, vendor, product all together

**Comment by oebs** [comment]
I tried now the second version of TWRP Test from 2020/09/29 and I see the System and Data partiotions in "Mount" menu, and at least "Data" in "Backup" and "Wipe / Advanced Wipe" menu., 
I can access the mobile with "adb devices" and "adb shell" as user root! I am not sure if this will possible every time, because it worked also with the first TWRP version. Later it did not show up anymore. Windows device problems?


```console
C:\adb\platform-tools> adb devices
List of devices attached
A7PRO205000511  recovery

C:\adb\platform-tools> adb shell

A7_pro:/ # id
uid=0(root) gid=0(root) groups=0(root),1004(input),1007(log),1011(adb),1015(sdcard_rw),1028(sdcard_r),3001(net_bt_admin),3002(net_bt),3003(inet),3006(net_bw_stats),3009(readproc),3011(uhid) context=u:r:su:s0
A7_pro:/ # df -h
Filesystem            Size  Used Avail Use% Mounted on
tmpfs                 1.9G  396K  1.9G   1% /dev
tmpfs                 1.9G     0  1.9G   0% /mnt
tmpfs                 1.9G     0  1.9G   0% /apex
tmpfs                 1.9G  131M  1.7G   7% /tmp
/dev/block/mmcblk0p37 110G   25G   85G  23% /data
/dev/block/mmcblk0p35 402M  5.3M  397M   2% /cache
/dev/block/loop0      836K  808K   28K  97% /apex/com.google.android.tzdata.apex
/dev/block/loop1      5.2M  5.2M   32K 100% /apex/com.google.android.media.apex
/dev/block/loop2       95M   95M   36K 100% /apex/com.android.runtime.release.apex
/dev/block/loop3      232K   36K  196K  16% /apex/com.android.apex.cts.shim.apex
/dev/block/loop4      2.2M  2.2M   32K  99% /apex/com.google.android.resolv.apex
/dev/block/loop5      4.9M  4.9M   28K 100% /apex/com.google.android.conscrypt.apex
/dev/block/loop6       21M   21M   32K 100% /apex/com.google.android.media.swcodec.apex
/dev/block/mmcblk1p1   59G   15G   44G  26% /external_sd
```
